### ISSUE TITLE
Rapport v3 avec l'imperméabilisation des sols

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#342]
### Situation actuelle

Rapport local v2 avec les indicateurs sur la consommation d'espaces + artificialisation des sols/. 

### Situation souhaitée

Rapport local v3 avec l'indicateur 3 sur l'imperméabilisation des sols.

https://docs.google.com/document/d/1enXF3iqHOtyU1FMDL7jVPT_IlHkyFtyc/edit?usp=sharing&ouid=107690444989310422470&rtpof=true&sd=true

Elements relatifs à l'indicateur 3 à changer par rapport à l'export complet : 
- [x] MAJ texte concernant l'imperméabilisation
- [x] Ajout graphique + tableau de données #458 
- [x] Ajout graphique + tableau de données #459 
-  [x]  Ajout graphique + tableau de données #460 
- [ ] Création page ou section imperméabilisation #461
